package com.nustnest.backend.notes;

public enum Subject {

    CS_212_OOP,
    EE_122_COMPUTER_ARCHITECTURE_AND_LOGIC_DESIGN,
    MATH_161_DISCRETE_MATHEMATICS,
    MATH_121_LINEAR_ALGEBRA_AND_ORDINARY_DIFFERENTIAL_EQUATIONS,
    HU_114_FUNCTIONAL_ENGLISH,
    HU_132_UNDERSTANDING_OF_QURAN
}
